"""Discovered dbt artifact schema versions — generated by ``codegen dbt``.

Maps each artifact family to the schema versions published at
``schemas.getdbt.com``. Refreshed by ``codegen dbt --discover`` (which probes the
site); do not edit by hand.
"""

VERSIONS: dict[str, tuple[str, ...]] = {
    "catalog": ("v1",),
    "manifest": (
        "v1",
        "v2",
        "v3",
        "v4",
        "v5",
        "v6",
        "v7",
        "v8",
        "v9",
        "v10",
        "v11",
        "v12",
    ),
    "run-results": (
        "v1",
        "v2",
        "v3",
        "v4",
        "v5",
        "v6",
    ),
    "sources": (
        "v1",
        "v2",
        "v3",
    ),
}
